config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :urls, only: [:new, :create, :show]
  get '/:short_url', to: 'urls#redirect', as: 'short_url_redirect'
  root to: 'urls#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
  validates :long_url, presence: true
  validates :short_url, uniqueness: true

  before_validation :generate_short_url

  def generate_short_url
    self.short_url = SecureRandom.hex(4)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    if @url.save
      redirect_to @url, notice: 'URL was successfully shortened.'
    else
      render :new
    end
  end

  def show
    @url = Url.find(params[:id])
  end

  def redirect
    @url = Url.find_by(short_url: params[:short_url])
    if @url
      redirect_to @url
    else
      redirect_to root_path, alert: 'Invalid shortened URL.'
    end
  end

  private

  def url_params
    params.require(:url).permit(:long_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/new.html.erb
<h1>URL Shortener</h1>

<%= form_with(model: @url, url: urls_path, method: :post) do |form| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this URL from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :long_url %>
    <%= form.text_field :long_url %>
  </div>

  <div class="actions">
    <%= form.submit 'Shorten URL' %>
  </div>
<% end %>

app/views/urls/show.html.erb
<h1>Shortened URL</h1>

<p>
  Long URL: <%= @url.long_url %><br>
  Short URL: <%= link_to short_url_redirect_url(@url.short_url) %>
</p>